// Английский словарь окна: русская строка из скриптов и со страницы → перевод.
// В строках с подстановками «{}» — место подстановки по порядку, {0}, {1} — по номеру.
window.MODVAULT_EN = {
  " · {}/с": " · {}/s",
  " · осталось {}": " · {} left",
  " Включены: ": " Enabled: ",
  " Уже найден {} — он включён во всех шагах; ищется, с кем вместе он вызывает проблему.": " Already found: {} — it stays enabled in every step; searching for what it causes the problem together with.",
  " и ": " and ",
  " — в наборах: ": " — in sets: ",
  " — нет на Nexus, ищите сами": " — not on Nexus, find it yourself",
  " — похоже, проблема осталась.": " — it looks like the problem remains.",
  " — похоже, проблемы нет.": " — it looks like there is no problem.",
  " — щёлкните, чтобы открыть подробности": " — click to see details",
  "Щёлкните, чтобы открыть пояснение": "Click to see the explanation",
  "Ctrl + щелчок или Shift + щелчок — выделить несколько модов, Ctrl + A — все видные, чтобы собрать из них набор. Правая кнопка мыши на моде — убрать из набора, добавить или перенести в другой. Щелчок по названию столбца сортирует список.": "Ctrl + click or Shift + click — select several mods, Ctrl + A — all shown ones, to make a set of them. Right-click a mod — remove it from the set, add or move it to another. Click a column name to sort the list.",
  "{} МБ": "{} MB",
  "{} из {}": "{} of {}",
  "{} мин": "{} min",
  "{} с": "{} s",
  "{} ч {} мин": "{} h {} min",
  "{} человек, всего скачиваний: {}": "{} people, total downloads: {}",
  "{}.\n\nНе хватает:\n{}": "{}.\n\nMissing:\n{}",
  "«+» — файл ляжет в игру, «~» — заменит прежний, «−» — уберётся.": "“+” — the file goes into the game, “~” — replaces the previous one, “−” — is removed.",
  "«{}» появится на этапе {}": "“{}” will appear at stage {}",
  "Автор": "Author",
  "Автор станет известен после проверки обновлений": "The author will be known after an update check",
  "Безвреден": "Harmless",
  "В игре только загрузчик модов и фреймворк: если проблема осталась и так, дело не в модах.": "Only the mod loader and the framework are in the game: if the problem remains even so, mods are not the cause.",
  "В избранное: мод будет стоять вверху списка": "Add to favourites: the mod will stay at the top of the list",
  "В новый набор…": "To a new set…",
  "В очереди": "Queued",
  "В этом запуске программы загрузок не было. Моды скачиваются кнопкой «Mod Manager Download» на сайте Nexus или значком обновления в списке модов; прошлые загрузки записаны в журнале.": "No downloads in this run of the program. Mods are downloaded with the “Mod Manager Download” button on the Nexus site or with the update icon in the mod list; past downloads are recorded in the journal.",
  "Вернуть Vortex": "Return to Vortex",
  "Версии «{}» в хранилище": "Versions of “{}” in the store",
  "Версии…": "Versions…",
  "Версий в хранилище": "Versions in the store",
  "Версия": "Version",
  "Версия меняется…": "Changing the version…",
  "Вкл.": "On",
  "Включить": "Enable",
  "Включить ": "Enable ",
  "Включить в наборе «{}»": "Enable in set “{}”",
  "Включить выделенные моды в наборе": "Enable the selected mods in a set",
  "Включён в наборах: ": "Enabled in sets: ",
  "Включённые": "Enabled",
  "Все": "All",
  "Все категории": "All categories",
  "Вы одобрили этот мод на Nexus — щёлкните, чтобы снять одобрение": "You have endorsed this mod on Nexus — click to withdraw the endorsement",
  "Выбранный мод": "Selected mod",
  "Выделено модов: {}": "Mods selected: {}",
  "Выделено: {} {}": "Selected: {} {}",
  "Выключенные": "Disabled",
  "Выключить": "Disable",
  "Выключить ": "Disable ",
  "Выключить «{}»": "Disable “{}”",
  "Готово · {}": "Done · {}",
  "Демонстрационные данные: хранилище пусто. Добавьте мод, и они исчезнут": "Demo data: the store is empty. Add a mod and it will disappear",
  "Добавить в набор": "Add to set",
  "Добавить в набор ▾": "Add to set ▾",
  "Добавить мод": "Add mod",
  "Добавляю из архивов: {}…": "Adding from archives: {}…",
  "Доступна": "Available",
  "Других версий нет: прежняя появится после обновления": "No other versions: the previous one will appear after an update",
  "Других наборов пока нет": "No other sets yet",
  "Если проблема повторится — виновник он. Если нет — её вызывают несколько модов вместе, и поиск продолжится.": "If the problem repeats, this mod is the culprit. If not, several mods cause it together and the search will go on.",
  "Если проблема повторится — её вызывают эти моды вместе.": "If the problem repeats, these mods cause it together.",
  "Ждёт решения": "Awaiting decision",
  "Журнал": "Journal",
  "Журнал пуст: программа ещё ничего не делала с модами и игрой.": "The journal is empty: the program has not done anything with mods or the game yet.",
  "Журналы игры": "Game logs",
  "Зависит от": "Depends on",
  "Загрузить коллекцию Nexus…": "Load Nexus collection…",
  "Загрузить набор из файла…": "Load a set from a file…",
  "Загрузка: {}{}": "Download: {}{}",
  "Загрузки": "Downloads",
  "Закрыть": "Close",
  "Замечаний нет: всё в порядке": "No issues: everything is fine",
  "Запустите игру и посмотрите, повторяется ли проблема. Потом ответьте здесь. ": "Run the game and see whether the problem repeats. Then answer here. ",
  "Знак ZD": "ZD mark",
  "Игра": "Game",
  "Игра запускается": "The game is starting",
  "Игра падает или ведёт себя странно, а виновник неизвестен: программа найдёт его за несколько запусков": "The game crashes or behaves strangely and the culprit is unknown: the program will find it in a few runs",
  "Играть": "Play",
  "Идёт · {}{}": "In progress · {}{}",
  "Избранные": "Favourites",
  "Изменить": "Change",
  "Источник:": "Source:",
  "Какие столбцы показывать": "Which columns to show",
  "Категории появятся после проверки обновлений": "Categories will appear after an update check",
  "Категория": "Category",
  "Категория на Nexus": "Category on Nexus",
  "Категория станет известна после проверки обновлений": "The category will be known after an update check",
  "Категория ▾": "Category ▾",
  "Когда эта версия мода добавлена в хранилище": "When this version of the mod was added to the store",
  "Коллекция: спрашиваю у Nexus её состав…": "Collection: asking Nexus for its contents…",
  "Конфликтов нет: моды не меняют одни и те же файлы.": "No conflicts: mods do not change the same files.",
  "Конфликты файлов": "File conflicts",
  "Личное сообщение на Nexus тому, кто выложил «{}»{}, от вашего имени.\n": "A private message on Nexus to the uploader of “{}”{}, in your name.\n",
  "Мод": "Mod",
  "Мод добавлен в хранилище": "Mod added to the store",
  "Моды": "Mods",
  "На Nexus есть версия ": "Nexus has version ",
  "Набор": "Set",
  "Набор «{}»: игра приводится к нему…": "Set “{}”: bringing the game to it…",
  "Набор загружен, но модов не хватает": "The set is loaded, but some mods are missing",
  "Набор по коллекции создан, но модов не хватает": "The set was created from the collection, but some mods are missing",
  "Набор:": "Set:",
  "Наборы": "Sets",
  "Наборы модов": "Mod sets",
  "Наборы модов: выбрать, создать, переименовать": "Mod sets: choose, create, rename",
  "Нажмите «Проверить обновления»": "Press “Check for updates”",
  "Название мода или автор": "Mod name or author",
  "Найдено сочетание модов": "A combination of mods found",
  "Найти сбойный мод": "Find faulty mod",
  "Написать автору": "Write to author",
  "Настройки": "Settings",
  "Настройки появятся, когда будет выбрана папка игры.": "Settings will appear once the game folder is chosen.",
  "Начало работы": "Getting started",
  "Не включён ни в одном наборе": "Not enabled in any set",
  "Не проверен": "Not checked",
  "Не удалось · {}": "Failed · {}",
  "Несколько модов кладут в игру один и тот же файл; остаётся вариант победителя. Щёлкните конфликт, чтобы разобрать его.": "Several mods put the same file into the game; the winner's version remains. Click a conflict to sort it out.",
  "Нет на Nexus": "Not on Nexus",
  "Ничего не найдено.": "Nothing found.",
  "Новый набор — копия текущего…": "New set — a copy of the current one…",
  "Обновить «{}» до {}": "Update “{}” to {}",
  "Обновить до ": "Update to ",
  "Обновление": "Update",
  "Обновление: запрос к Nexus…": "Update: asking Nexus…",
  "Одобрений": "Endorsements",
  "Одобрений на Nexus: {}": "Endorsements on Nexus: {}",
  "Одобрить мод на Nexus": "Endorse the mod on Nexus",
  "Ответ придёт в личные сообщения на сайте: в программе он не появится.": "The reply will come to your private messages on the site: it will not appear in the program.",
  "Открыть": "Open",
  "Открыть на Nexus": "Open on Nexus",
  "Открыть профиль {} на Nexus": "Open the profile of {} on Nexus",
  "Загрузки, ошибки и обсуждения на GitHub": "Downloads, issues and discussions on GitHub",
  "Открыть страницы на Nexus ({})": "Open pages on Nexus ({})",
  "Отмена": "Cancel",
  "Отправить": "Send",
  "Отсортировать по правилам": "Sort by rules",
  "Ошибка": "Error",
  "Ошибок в прошлом запуске игры: {}. Первая: {}": "Errors in the last game run: {}. First: {}",
  "Папка игры": "Game folder",
  "Переименовать «{}»…": "Rename “{}”…",
  "Перенести из «{}» в набор": "Move from “{}” to set",
  "Переставлять моды можно, когда список стоит в порядке загрузки: щёлкните по столбцу «№»": "Mods can be rearranged when the list is in load order: click the “№” column",
  "План по файлам": "Plan by files",
  "Подключения": "Connections",
  "Поиск по названию или автору": "Search by name or author",
  "Поиск сбойного мода": "Faulty mod search",
  "Поиск сбойного мода закончен": "Faulty mod search finished",
  "Поиск сбойного мода: игра приводится к следующему шагу…": "Faulty mod search: bringing the game to the next step…",
  "Показано {} из {}": "Shown {} of {}",
  "Показать по файлам": "Show by files",
  "Показать файлы": "Show files",
  "Порядок загрузки": "Load order",
  "После обновления в хранилище остаётся одна прежняя версия: к ней можно вернуться.": "After an update one previous version stays in the store: you can return to it.",
  "Потяните, чтобы переставить мод в порядке загрузки": "Drag to move the mod in the load order",
  "Прервать поиск": "Stop search",
  "Проблема осталась": "Problem remains",
  "Проблему вызывает «{}»: она повторилась, когда в игре был включён только он.\n\nВыключить его в наборе «{}»? Остальные моды останутся как были.": "“{}” causes the problem: it repeated when only this mod was enabled in the game.\n\nDisable it in set “{}”? The other mods stay as they were.",
  "Проблему вызывают вместе: {}. По отдельности они её не дают.\n\nЧтобы проблема ушла, достаточно выключить любой из них в наборе «{}».": "These cause the problem together: {}. Separately they do not.\n\nTo make the problem go away it is enough to disable any one of them in set “{}”.",
  "Проблемы нет": "No problem",
  "Проверить обновления": "Check for updates",
  "Проверка обновлений при запуске не удалась: ": "The update check on start failed: ",
  "Проверка обновлений: ": "Update check: ",
  "Проверка обновлений: запрос к Nexus…": "Update check: asking Nexus…",
  "Проверяется": "Checking",
  "Программа не может работать с хранилищем: ": "The program cannot work with the store: ",
  "Программа сузит круг.": "The program will narrow the circle.",
  "Развернуть": "Deploy",
  "Развёртывание…": "Deploying…",
  "Разделы": "Sections",
  "Рейтинг": "Rating",
  "Решён": "Resolved",
  "С обновлением": "With update",
  "С ошибками": "With errors",
  "С частью модов проблема ни разу не повторилась: программа проверяет, что с полным набором она есть.": "With part of the mods the problem never repeated: the program checks that it is there with the full set.",
  "Сбойный мод найден": "Faulty mod found",
  "Сбросить": "Reset",
  "Скачали": "Users",
  "Сколько пользователей Nexus одобрили мод": "How many Nexus users endorsed the mod",
  "Сколько разных людей скачали мод с Nexus": "How many different people downloaded the mod from Nexus",
  "Скрыто замечаний: {}": "Hidden issues: {}",
  "Скрыть": "Hide",
  "Скрыть файлы": "Hide files",
  "Снять выделение": "Clear selection",
  "Состояние": "State",
  "Сохранить «{}» в файл…": "Save “{}” to a file…",
  "Статистика появится после проверки обновлений": "Statistics will appear after an update check",
  "Столбцы таблицы": "Table columns",
  "Страница мода на Nexus убрана или скрыта автором": "The mod page on Nexus was removed or hidden by the author",
  "Страница открыта вне программы: данных нет": "The page is opened outside the program: no data",
  "Текст": "Text",
  "Тема": "Subject",
  "Требуют внимания": "Needs attention",
  "У мода нет номера на Nexus": "The mod has no Nexus number",
  "У мода нет номера на Nexus: автор неизвестен": "The mod has no Nexus number: the author is unknown",
  "У мода нет номера на Nexus: проверить его нельзя": "The mod has no Nexus number: it cannot be checked",
  "У мода нет номера на Nexus: статистики нет": "The mod has no Nexus number: no statistics",
  "Убрать из избранного": "Remove from favourites",
  "Убрать из набора «{}»": "Remove from set “{}”",
  "Убрать это замечание из списка. Вернуть скрытые можно ссылкой под списком": "Remove this issue from the list. Hidden ones can be brought back with the link under the list",
  "Удалить мод": "Delete mod",
  "Удалить набор «{}»": "Delete set “{}”",
  "Установлен": "Installed",
  "Установлена": "Version",
  "Установлена последняя версия с Nexus": "The latest version from Nexus is installed",
  "Файлов": "Files",
  "Хранилище модов": "Mod store",
  "Хранилище: ": "Store: ",
  "Шаг {} из примерно {}: под подозрением {}, сейчас включено {}": "Step {} of about {}: {} suspects, {} enabled now",
  "Шаг {}: ": "Step {}: ",
  "Эта версия добавлена ": "This version was added ",
  "безвреден: файлы одинаковые": "harmless: the files are identical",
  "в хранилище: {}": "in the store: {}",
  "включено: {}": "enabled: {}",
  "включены все моды набора": "all mods of the set are enabled",
  "всегда": "always",
  "два варианта одного мода": "two variants of one mod",
  "добавлена ": "added ",
  "контрольный — включены только {}": "control run — only {} enabled",
  "млн": "M",
  "мод|мода|модов": "mod|mods",
  "моды набора выключены": "mods of the set are disabled",
  "один мод перекрыт целиком": "one mod is fully overridden",
  "поделиться": "share",
  "показать": "show",
  "порядок указал автор": "order stated by the author",
  "тыс.": "K",
  "убрать": "remove",
  "файлов: {} · {} · побеждает {}": "files: {} · {} · winner: {}",
  "частичное пересечение": "partial overlap",
  "★ В избранное": "★ Add to favourites",
  "☆ Убрать из избранного": "☆ Remove from favourites",
  "♡ Одобрить на Nexus": "♡ Endorse on Nexus",
  "♥ Снять одобрение на Nexus": "♥ Withdraw endorsement on Nexus",
  "⚙ Столбцы": "⚙ Columns",
  "✉ Написать автору…": "✉ Write to author…",
  "✓ Актуально": "✓ Up to date",
  "Открыть папку проекта": "Open project folder",
  "Взять в Modvault": "Take into Modvault",
  "Мод вне Modvault: его место в порядке загрузки решает загрузчик": "Mod outside Modvault: the loader decides its place in the load order",
  "Мод лежит в игре вне Modvault, игра грузит его всегда. Возьмите его в Modvault, чтобы выключать и включать в наборы": "The mod is in the game outside Modvault, and the game always loads it. Take it into Modvault to disable it and add it to sets",
  "Мод переходит в хранилище…": "Moving the mod into the store…",
  "Подключить как мод в разработке": "Connect as a mod in development",
  "вне": "outside",
  "Нужен модам": "Needed by",
  "Нужен модам: ": "Needed by: ",
  "Требует: ": "Requires: ",
  "Конфликт файлов: {} — щёлкните, чтобы разобрать": "File conflicts: {} — click to resolve",
  "Мод в разработке: в игре ссылка на {}": "Mod in development: the game has a link to {}",
  "Мод добавлен с диска": "Mod added from disk",
  "Мод с Nexus Mods": "Mod from Nexus Mods",
  "Положен в игру вручную, вне Modvault": "Put into the game by hand, outside Modvault",
  "Ссылка на папку вне Modvault: {}": "Link to a folder outside Modvault: {}",
  "кому нужен он": "who needs it",
  "конфликт файлов": "file conflict",
  "нужен другим": "needed by others",
  "положен вручную": "put by hand",
  "с Nexus": "from Nexus",
  "с диска": "from disk",
  "ссылка на папку проекта": "link to a project folder",
  "требует другие моды": "requires other mods",
  "у выбранного: что ему нужно": "for the selected mod: what it needs"
};
